# Define sample names
#samples: ["GL_R10_GL11_UP_3","GL_R11_GL15_UP_1","GL_R12_GL15_UP_2","GL_R13_GL15_UP_3","GL_R17_GL16_UP_1","GL_R18_GL16_UP_2","GL_R19_GL16_UP_3"]

# Directory where fastq files are
data_dir: "/mnt/esb-storage-01/NOMIS/NovaSeq_20200624_NOV395_o7028_DataDelivery/"

# Directory to save the output to
results_dir: "/mnt/md1200/epfl_sber/greg/coassembly/"

# deduplicated directory
dedup_dir: "/mnt/md1200/epfl_sber/greg/coassembly/dedup"

# Directory for all the conda environments
env_dir: "/home/gregoire.michoud/NOMIS_ENSEMBLE/envs"

# Number of cpus or threads to use
threads: 30

# Preprocessing
fastp:
    threads: 12
    min_length: 40

# FastQ QC
# https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
fastqc:
    threads: 12
    params: "-q -f fastq"

# De-duplication
clumpify:
    threads: 7
    dupedist: 12000
    groups: auto
    memory: "600g"

kraken2:
    db: "/mnt/esb-storage-01/NOMIS/maxikraken2_1903_140GB/"
    threads: 8

# Assembly
megahit:
    threads: 50

coverm:
    threads: 50

concoct:
    threads: 8
