# Define the sample names
# samples: ["Unassigned"]

# Working directory path
data_dir: "/mnt/md1200/epfl_sber/massimo/EUCI_MG/selection_inference/sbusi/clusters"

# Path to results directory
results_dir: "/mnt/md1200/epfl_sber/massimo/EUCI_MG/selection_inference/sbusi/clusters"
